# Generated by Django 3.2 on 2022-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_workingtime', models.TimeField(default='09:00')),
                ('finish_workingtime', models.TimeField(default='18:00')),
                ('people_per_hour', models.IntegerField(default=5)),
                ('deadline_day', models.IntegerField(default=30)),
            ],
        ),
    ]
