# Generated by Django 3.2 on 2022-08-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_info',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop_info',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
