# Generated by Django 3.2 on 2022-08-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_auto_20220815_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='staff',
            new_name='user',
        ),
    ]
