# Generated by Django 3.2 on 2022-08-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_rename_staff_shift_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_info',
            name='deadline_day',
            field=models.IntegerField(default=30, verbose_name='シフト提出締切日（何日前）'),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='people_per_hour',
            field=models.IntegerField(default=5, verbose_name='一時間当たりの人数'),
        ),
    ]
