# Generated by Django 3.2 on 2022-09-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0006_auto_20220818_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='workingtime',
            field=models.DateTimeField(verbose_name='シフト時間'),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True, verbose_name='電話番号'),
        ),
    ]
