# Generated by Django 3.2 on 2022-08-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clerk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerkname',
            field=models.CharField(default='clerk', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='personalimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
