# Generated by Django 3.2 on 2022-08-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220809_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
