# Generated by Django 3.2 on 2022-08-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userr_clerkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='clerkname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
