# Generated by Django 3.2 on 2022-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userr_clerkname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='admin_only_text',
            field=models.CharField(default='管理者のみ閲覧可。', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userr',
            name='introduction_text',
            field=models.CharField(default='自己紹介文', max_length=200),
        ),
    ]
