# Generated by Django 3.2 on 2022-08-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220810_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clerk',
        ),
    ]
