# Generated by Django 3.2 on 2022-08-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_clerk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='personalimage',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='プロフィール画像'),
        ),
    ]
