# Generated by Django 3.2 on 2022-08-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userr_personalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='category',
            field=models.IntegerField(default=0, verbose_name='ユーザー種別'),
        ),
    ]
