# Generated by Django 3.2 on 2022-09-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userr_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userr',
            options={'verbose_name': 'user'},
        ),
    ]
